;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.byte 2
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256

@instruments:
	.byte $f0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env3,@env0,@env4
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$cd,$cb,$c9,$c6,$c4,$c2,$c0,$00,$07
@env2:
	.byte $cf,$ca,$c5,$c0,$00,$03
@env3:
	.byte $cf,$00,$00
@env4:
	.byte $ff,$00,$00


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $80,$4b,$4a,$4a,$4b,$4a,$4a,$4b,$4a,$4a,$4b,$4a,$81
@ref1:
	.byte $4b,$4a,$4a,$4b,$4a,$4a,$4b,$4a,$4a,$4b,$4a,$81
	.byte $ff,$0c
	.word @ref1
	.byte $ff,$0c
	.word @ref1
	.byte $ff,$0c
	.word @ref1
	.byte $ff,$0c
	.word @ref1
	.byte $ff,$0c
	.word @ref1
	.byte $ff,$0c
	.word @ref1
	.byte $ff,$0c
	.word @ref1
	.byte $ff,$0c
	.word @ref1
	.byte $ff,$0c
	.word @ref1
	.byte $ff,$0c
	.word @ref1
	.byte $ff,$0c
	.word @ref1
	.byte $ff,$0c
	.word @ref1
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref14:
	.byte $80,$59,$58,$58,$59,$58,$58,$59,$58,$58,$59,$58,$81
@ref15:
	.byte $59,$58,$58,$59,$58,$58,$59,$58,$58,$59,$58,$81
	.byte $ff,$0c
	.word @ref15
	.byte $ff,$0c
	.word @ref15
	.byte $ff,$0c
	.word @ref15
	.byte $ff,$0c
	.word @ref15
	.byte $ff,$0c
	.word @ref15
	.byte $ff,$0c
	.word @ref15
	.byte $ff,$0c
	.word @ref15
	.byte $ff,$0c
	.word @ref15
	.byte $ff,$0c
	.word @ref15
	.byte $ff,$0c
	.word @ref15
	.byte $ff,$0c
	.word @ref15
	.byte $ff,$0c
	.word @ref15
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref28:
	.byte $9f
@ref29:
	.byte $9f
@ref30:
	.byte $9f
@ref31:
	.byte $80,$4b,$4b,$63,$63,$4b,$4b,$4b,$62,$81
@ref32:
	.byte $4b,$4b,$63,$63,$4b,$4b,$4b,$62,$81
	.byte $ff,$09
	.word @ref32
	.byte $ff,$09
	.word @ref32
	.byte $ff,$09
	.word @ref32
	.byte $ff,$09
	.word @ref32
	.byte $ff,$09
	.word @ref32
	.byte $ff,$09
	.word @ref32
	.byte $ff,$09
	.word @ref32
	.byte $ff,$09
	.word @ref32
	.byte $ff,$09
	.word @ref32
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref42:
	.byte $82,$0f,$0b,$0f,$05,$21,$03,$0b,$04,$81
@ref43:
	.byte $0f,$0b,$0f,$05,$21,$03,$0b,$04,$81
	.byte $ff,$09
	.word @ref43
	.byte $ff,$09
	.word @ref43
	.byte $ff,$09
	.word @ref43
	.byte $ff,$09
	.word @ref43
	.byte $ff,$09
	.word @ref43
	.byte $ff,$09
	.word @ref43
	.byte $ff,$09
	.word @ref43
	.byte $ff,$09
	.word @ref43
	.byte $ff,$09
	.word @ref43
	.byte $ff,$09
	.word @ref43
	.byte $ff,$09
	.word @ref43
	.byte $ff,$09
	.word @ref43
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref56:
	.byte $9f
@ref57:
	.byte $9f
@ref58:
	.byte $9f
@ref59:
	.byte $9f
@ref60:
	.byte $9f
@ref61:
	.byte $9f
@ref62:
	.byte $9f
@ref63:
	.byte $9f
@ref64:
	.byte $9f
@ref65:
	.byte $9f
@ref66:
	.byte $9f
@ref67:
	.byte $9f
@ref68:
	.byte $9f
@ref69:
	.byte $9f
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$0b
@song1ch0loop:
@ref70:
	.byte $9f
@ref71:
	.byte $9f
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref72:
	.byte $9f
@ref73:
	.byte $9f
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref74:
	.byte $84,$58,$4a,$01,$4a,$5c,$00,$60,$4a,$00,$58,$4a,$01,$52,$4a
@ref75:
	.byte $01,$58,$4a,$01,$60,$4a,$00,$4a,$5c,$00,$58,$4a,$00,$81
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref76:
	.byte $9f
@ref77:
	.byte $9f
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref78:
	.byte $9f
@ref79:
	.byte $9f
	.byte $fd
	.word @song1ch4loop
