; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses FamiTracker tempo, you must set FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_cowboy_guns=music_data_cowboy_guns
.endif

music_data_cowboy_guns:
	.byte 2
	.word @instruments
	.word @samples-4
; 00 : Gamble
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256
; 01 : Cowboys
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.word 307,256

.export music_data_cowboy_guns
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env2,@env4,@env6,@env0 ; 00 : instrument0
	.word @env3,@env4,@env5,@env7 ; 01 : iii
	.word @env1,@env4,@env5,@env0 ; 02 : instrument1

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$ca,$c5,$c0,$00,$04
@env2:
	.byte $00,$cf,$cd,$cb,$c9,$c6,$c4,$c2,$c0,$00,$08
@env3:
	.byte $00,$cf,$7f,$00,$02
@env4:
	.byte $c0,$7f,$00,$01
@env5:
	.byte $7f,$00,$00
@env6:
	.byte $c1,$7f,$00,$00
@env7:
	.byte $80,$ff,$c0,$00,$02

@samples:

@song0ch0:
	.byte $46, $0b
@song0ch0loop:
	.byte $9f, $9f, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $9f, $9f, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $82, $2c, $25, $00, $81, $25, $2e, $00, $30, $25, $00, $2c, $25, $00, $81, $29, $25, $00, $81, $2c, $25, $00, $81, $30
	.byte $25, $00, $25, $2e, $00, $2c, $25, $00, $81, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $9f, $9f, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $9f, $9f, $42
	.word @song0ch4loop
@song1ch0:
	.byte $46, $06, $80
@song1ref4:
	.byte $22, $81, $22, $22, $22, $81, $22, $22, $22, $81, $22, $22, $22, $81, $22, $81, $24, $81, $24, $24, $24, $81, $24, $24
	.byte $24, $81, $24, $24, $24, $81, $24, $81, $25, $81, $25, $25, $25, $81, $25, $25, $25, $81, $25, $25, $25, $81, $25, $81
	.byte $24, $81, $24, $24, $24, $81, $24, $24, $24, $81, $24, $24, $24, $81, $24, $81
	.byte $41, $40
	.word @song1ref4
@song1ch0loop:
	.byte $41, $40
	.word @song1ref4
	.byte $41, $40
	.word @song1ref4
	.byte $41, $40
	.word @song1ref4
	.byte $42
	.word @song1ch0loop
@song1ch1:
	.byte $80
@song1ref85:
	.byte $1e, $81, $1e, $1e, $1e, $81, $1e, $1e, $1e, $81, $1e, $1e, $1e, $81, $1e, $81, $20, $81, $20, $20, $20, $81, $20, $20
	.byte $20, $81, $20, $20, $20, $81, $20, $81
	.byte $41, $20
	.word @song1ref85
	.byte $41, $20
	.word @song1ref85
	.byte $41, $20
	.word @song1ref85
@song1ch1loop:
	.byte $41, $20
	.word @song1ref85
	.byte $41, $20
	.word @song1ref85
	.byte $41, $20
	.word @song1ref85
	.byte $41, $20
	.word @song1ref85
	.byte $41, $20
	.word @song1ref85
	.byte $41, $20
	.word @song1ref85
	.byte $42
	.word @song1ch1loop
@song1ch2:
	.byte $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f
@song1ch2loop:
	.byte $80
@song1ref158:
	.byte $3c, $81, $3b, $81, $3a, $81, $39, $81, $3c, $81, $3b, $81, $3a, $81, $39, $81, $3c, $81, $3b, $81, $3a, $81, $39, $81
	.byte $3c, $81, $3b, $81, $3a, $81, $39, $81, $40, $4d, $81, $40, $4c, $81, $3f, $81, $3e, $81, $40, $4d, $81, $40, $4c, $81
	.byte $3f, $81, $3e, $81, $40, $4d, $81, $40, $4c, $81, $3f, $81, $3e, $81, $40, $4d, $81, $40, $4c, $81, $3f, $81, $3e, $81
	.byte $41, $40
	.word @song1ref158
	.byte $00, $9d, $9f, $9f, $9f, $42
	.word @song1ch2loop
@song1ch3:
	.byte $84
@song1ref242:
	.byte $1e, $81, $1c, $1c, $1e, $81, $1c, $1c, $1e, $81, $1c, $1c, $1e, $81, $1c, $81, $1e, $81, $1c, $1c, $1e, $81, $1c, $1c
	.byte $1e, $81, $1c, $1c, $1e, $81, $1c, $81
	.byte $41, $20
	.word @song1ref242
	.byte $41, $20
	.word @song1ref242
	.byte $41, $20
	.word @song1ref242
@song1ch3loop:
	.byte $41, $20
	.word @song1ref242
	.byte $41, $20
	.word @song1ref242
	.byte $41, $20
	.word @song1ref242
	.byte $41, $20
	.word @song1ref242
	.byte $41, $20
	.word @song1ref242
	.byte $41, $20
	.word @song1ref242
	.byte $42
	.word @song1ch3loop
@song1ch4:
	.byte $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f
@song1ch4loop:
	.byte $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $9f, $42
	.word @song1ch4loop
