; This file is for the FamiStudio Sound Engine and was generated by FamiStudio


.if FAMISTUDIO_CFG_C_BINDINGS
.export _sounds=sounds
.endif

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_shoot
	.word @sfx_ntsc_reload

@sfx_ntsc_shoot:
	.byte $8a,$8a,$89,$3f,$01,$8a,$89,$01,$8a,$87,$01,$8a,$8a,$01,$8a,$8b
	.byte $89,$3b,$01,$8a,$8c,$01,$8a,$88,$01,$8a,$8b,$01,$8a,$8d,$89,$35
	.byte $01,$8a,$8c,$01,$8a,$8a,$01,$8a,$8d,$01,$8a,$8f,$00
@sfx_ntsc_reload:
	.byte $8a,$08,$89,$3f,$06,$8a,$06,$89,$3b,$06,$8a,$08,$89,$35,$06,$8a
	.byte $06,$00

.export sounds
