;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @ntsc
	.word @pal
@ntsc:
	.word @sfx_ntsc_0
@pal:
	.word @sfx_pal_0

@sfx_ntsc_0:
	.byte $89,$3f,$8a,$8a,$01,$8a,$89,$01,$8a,$87,$01,$8a,$8a,$01,$89,$3b
	.byte $8a,$8b,$01,$8a,$8c,$01,$8a,$88,$01,$8a,$8b,$01,$89,$35,$8a,$8d
	.byte $01,$8a,$8c,$01,$8a,$8a,$01,$8a,$8d,$01,$00
@sfx_pal_0:
	.byte $89,$3f,$8a,$8a,$01,$8a,$89,$01,$8a,$87,$01,$8a,$8a,$01,$89,$3b
	.byte $8a,$8b,$01,$8a,$8c,$01,$8a,$88,$01,$89,$35,$8a,$8d,$01,$8a,$8c
	.byte $01,$8a,$8a,$01,$00
